name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name "Gaurav Chaudhari"
          git config --global user.email "capristar02@gmail.com" 
      - run: git submodule update --remote --merge
      - run: git add --all
      - run: git commit -m "Modified submodule remote"
      - run: git push origin master 
