name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull code from subrepo
      run: |
        git subtree add --squash --prefix=subrepo/ subrepo master
